name: 🚀 Auto Deploy to KVM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build the app
        run: yarn build

      - name: Deploy to KVM2 via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/home/ptpinstitute/htdocs/www.ptpinstitute.com/TeacherGotHire-Frontend-/dist/"
          strip_components: 1

      - name: Restart Nginx or PM2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ptpinstitute/htdocs/www.ptpinstitute.com/TeacherGotHire-Frontend-
            pm2 restart ptp-webhook
