# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ptpiui

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: yarn install, build, and test
        run: |
          yarn install
          yarn run build

      - name: Create web.config file
        run: |
          echo ^<configuration^> > ./dist/web.config
          echo ^<system.webServer^> >> ./dist/web.config
          echo ^<rewrite^> >> ./dist/web.config
          echo ^<rules^> >> ./dist/web.config
          echo ^<rule name="SPA fallback" stopProcessing="true"^> >> ./dist/web.config
          echo ^<match url=".*" / ^> >> ./dist/web.config
          echo ^<conditions logicalGrouping="MatchAll"^> >> ./dist/web.config
          echo ^<add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" / ^> >> ./dist/web.config
          echo ^<add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" / ^> >> ./dist/web.config
          echo ^</conditions^> >> ./dist/web.config
          echo ^<action type="Rewrite" url="/" / ^> >> ./dist/web.config
          echo ^</rule^> >> ./dist/web.config
          echo ^</rules^> >> ./dist/web.config
          echo ^</rewrite^> >> ./dist/web.config
          echo ^</system.webServer^> >> ./dist/web.config
          echo ^</configuration^> >> ./dist/web.config
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'ptpiui'
          slot-name: 'Production'
          package: ./dist
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FE1D99DF3D874B08ADAAEB64404F9DEB }}